apiVersion: v1
kind: Service
metadata:
  name: kube-lab-service  
spec:
  type: NodePort  
  selector:
    app: kube-lab  
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 8080  
    nodePort: 30080 